main.go

Fixes https://github.com/alecthomas/gometalinter/issues/42

Support min confidence for golint

---

README.md
main.go

Removing the need for two `update` commands to be run

Add gometalinter to installMap

---

README.md

Should have been in previous commit/pull request, sorry.

Add missing line to README

---

README.md
main.go

Update help for `Default linters to "warning".` 

---

README.md

It takes interfaces from the given packages and their dependencies too.

README: interfacer is not limited to the std

---

README.md
main.go
regressiontests/goconst_test.go

Implement goconst

---

README.md
main.go

Add support for staticcheck.

---

main.go

A common pratice for linters is to provides a way to format output. This ease integration with editors and usablity in scripts. I don't know how you feel about adding formatting support to gometalinter so I made a basic implementation to discuss it.
This add a `--format` option. It uses a format string and `text/template` from the stdlib to render an issue line. The default format is retrocompatible with the previous behavior. I couldn't find a significant impact on performance.
What still missing is a basic documentation, at least the available fields.
What do you think?

make output format configurable

---

README.md

staticcheck isn't really just about checking arguments anymore, it's a generic static checker now.

Update description of staticcheck

---

vendor/manifest
vendor/src/github.com/kisielk/errcheck/internal/errcheck/errcheck.go
vendor/src/github.com/kisielk/errcheck/main.go
vendor/src/github.com/kisielk/gotool/match.go

Reason for upgrade explained in #198.
I've added all files, including optional ones (tests, README) - these may be removed if you like.

vendor: update errcheck

---

config.go
main.go

Feature for download only request

---

config.go
main.go

Was: {"Deadline": 60000000000}
Now: {"Deadline": "60s"}

json config: specify Deadline as string with time.Duration units

---

main.go

Add -h short flag for -help flag

---

README.md
_linters/src/github.com/stripe/safesql/LICENSE
_linters/src/github.com/stripe/safesql/package15.go
_linters/src/github.com/stripe/safesql/package16.go
_linters/src/github.com/stripe/safesql/safesql.go
_linters/src/golang.org/x/tools/go/callgraph/LICENSE
_linters/src/golang.org/x/tools/go/callgraph/callgraph.go
_linters/src/golang.org/x/tools/go/callgraph/cha/cha.go
_linters/src/golang.org/x/tools/go/callgraph/rta/rta.go
_linters/src/golang.org/x/tools/go/callgraph/static/static.go
_linters/src/golang.org/x/tools/go/callgraph/util.go
_linters/src/golang.org/x/tools/go/pointer/LICENSE
_linters/src/golang.org/x/tools/go/pointer/analysis.go
_linters/src/golang.org/x/tools/go/pointer/api.go
_linters/src/golang.org/x/tools/go/pointer/callgraph.go
_linters/src/golang.org/x/tools/go/pointer/constraint.go
_linters/src/golang.org/x/tools/go/pointer/doc.go
_linters/src/golang.org/x/tools/go/pointer/gen.go
_linters/src/golang.org/x/tools/go/pointer/hvn.go
_linters/src/golang.org/x/tools/go/pointer/intrinsics.go
_linters/src/golang.org/x/tools/go/pointer/labels.go
_linters/src/golang.org/x/tools/go/pointer/opt.go
_linters/src/golang.org/x/tools/go/pointer/print.go
_linters/src/golang.org/x/tools/go/pointer/reflect.go
_linters/src/golang.org/x/tools/go/pointer/solve.go
_linters/src/golang.org/x/tools/go/pointer/util.go
_linters/src/manifest
config.go
regressiontests/safesql_test.go

add safesql

---

README.md
_linters/src/github.com/mvdan/unparam/LICENSE
_linters/src/github.com/mvdan/unparam/main.go
_linters/src/manifest
config.go
regressiontests/unparam_test.go

Adds linter [mvdan/unparam](https://github.com/mvdan/unparam) (checking for unused function parameters).

add unparam

---

config.go
main.go
main_test.go

Reverts alecthomas/gometalinter#288

Revert "Use a duration type instead of deadline crutch"

---

README.md

Remove DisableAll from README

---

config.go
execute.go
main.go
main_test.go

Take 2 of #288, sorry about take 1.
I left the changes in a separate commit so it's easier to see what has changed. 
Testing manually with a deadline, I can see the correct value is printed. I've also added a test to cover the case that was broke by take 1.

Replace deadline crutch again

---

README.md

Sorry, I had the indentation wrong (and made a slight title change).

README: Correctly nest revgrep FAQ entry

---

README.md
config.go

Update README to remove reference to '{path}'

---

_linters/src/github.com/gordonklaus/ineffassign/ineffassign.go
_linters/src/manifest

Update ineffassign to support multiple paths

---

config.go
linters.go
regressiontests/gotype_test.go

Added gotypex linter to check external tests with gotype

---

README.md

Mention gotypex in README

---

.travis.yml

Test against multiple go versions

---

README.md
_linters/src/github.com/alexkohler/nakedret/LICENSE
_linters/src/github.com/alexkohler/nakedret/import.go
_linters/src/github.com/alexkohler/nakedret/nakedret.go
_linters/src/manifest
linters.go
regressiontests/nakedret_test.go

#372 Add support for nakedret

---

_linters/src/github.com/opennota/check/cmd/varcheck/varcheck.go
_linters/src/manifest

Update to include this fix: https://github.com/opennota/check/pull/41

Update varcheck to fix a bug

---

main.go

Fix vendor search path for v2

---

main.go

https://github.com/alecthomas/gometalinter/issues/406#issuecomment-350018730

Remove v1 from linter paths

---

main.go

This makes the usage output a little nicer.
Fixes #453.
Thank you!

Sort linters by name when formatting them

---

regressiontests/gas_test.go
regressiontests/gotype_test.go
regressiontests/support.go
regressiontests/vet_test.go

Change import "github.com/gotestyourself/gotestyourself/fs" to "gotest.tools/fs"

---

linters.go
linters_test.go

Improvements for test and testify linter

---

_linters/src/github.com/kisielk/errcheck/internal/errcheck/embedded_walker.go
_linters/src/github.com/kisielk/errcheck/internal/errcheck/errcheck.go
_linters/src/github.com/kisielk/errcheck/main.go
_linters/src/manifest

It contains useful updates, including suppressing warnings for Write
implementations that will never fail.

Update errcheck to e96dacdb078a5166c20b48dd667fb26d2ce0379

---

_linters/src/github.com/kisielk/errcheck/internal/errcheck/embedded_walker.go
_linters/src/github.com/kisielk/errcheck/internal/errcheck/errcheck.go
_linters/src/github.com/kisielk/errcheck/main.go
_linters/src/manifest

Reverts alecthomas/gometalinter#500

Revert "Revert "Update errcheck to e96dacdb078a5166c20b48dd667fb26d2ce0379""

---

README.md

Fix type on README

---

linters.go

Issue https://github.com/alecthomas/gometalinter/issues/510

Fix gosec errors multiplying

---

_linters/src/github.com/securego/gosec/cmd/gosec/main.go
_linters/src/github.com/securego/gosec/cmd/gosec/sort_issues.go
_linters/src/github.com/securego/gosec/helpers.go
_linters/src/github.com/securego/gosec/rules/blacklist.go
_linters/src/github.com/securego/gosec/rules/rulelist.go
_linters/src/github.com/securego/gosec/rules/sql.go
_linters/src/github.com/securego/gosec/rules/subproc.go
_linters/src/github.com/securego/gosec/rules/weakcrypto.go
_linters/src/github.com/securego/gosec/testutils/source.go
_linters/src/manifest

Update the vendored gosec

---

.travis.yml
regressiontests/vet_test.go

Adding Go 1.11 to travis to catch possible issues; I can update this PR when newer betas are released
/cc @dnephin @kolyshkin

Add go 1.11.0

---

.goreleaser.yml

As suggested here - https://github.com/alecthomas/gometalinter/issues/572 . Attempting to add power support. Could you please review/comments - @alecthomas

Adding power support

---

stringset.go

Do not resize slice when we now it's final size.

Reduce memory allocations
