alecthomas/gometalinter

README.md, main.go
When running `gometalinter`, I found it hard to fix the issues reported without knowing which linter they came from. This appends the linter name to the end of each line wrapped in parens.
example/stutter.go:9::warning: unused global variable unusedGlobal (varcheck)
example/stutter.go:21:15:warning: error return value not checked (defer a.Close()) (errcheck)
example/stutter.go:22:15:warning: error return value not checked (defer a.Close()) (errcheck)
example/stutter.go:27:6:warning: error return value not checked (doit()           // test for errcheck) (errcheck)
example/stutter.go:12:6:warning: exported type MyStruct should have comment or be unexported (golint)
example/stutter.go:16:6:warning: exported type PublicUndocumented should have comment or be unexported (golint) …
=> Append linter name to issue output

main.go
'i' will be nil and err will be non-nil in walkFn if the path does not exist.
=> Check for invalid paths in expandPaths(). 

main.go
From the `go get -help`: 
> The -f flag, valid only when -u is set, forces get -u not to verify that
each package has been checked out from the source control repository
implied by its import path. This can be useful if the source is a local fork
of the original.
=> Add -f flag to pass to the go tool when installing

README.md, example/stutter.go, main.go
- Implementation of `go tool vet --shadow` for reporting shadowed variables
- Remove the [deprecated](https://github.com/barakmich/go-nyet#deprecated) `go-nyet`
- Update the `README`
Fixes #28.
=> Replace go-nyet by go tool vet --shadow

README.md, main.go, regression_tests/gofmt_test.go
Right now it reports with a very simple message as suggested: `file is not gofmted`.
It might be interesting in the future to report the lines impacted (maybe with a generic flag `-v`?).
Fixes #37.
=> Implement gofmt

README.md, main.go, regression_tests/goimports_test.go
`goimport`'s output is overridden with a simple message: `file is not goimported`.
Fixes #38.
=> Implement goimports

main.go
=> Pass `-abspath` to errcheck to avoid broken paths

main.go
go get can takes multiple packages so install them at
the same time.  Since many binaries use the same packages
it saves us rechecking packages multiple times.  More important
during a --update step.
=> Speed up install step

main.go
By adding this option, editors have a way to run `gometalinter` and only output the results for the file being saved. Of course it also helps other use cases where you only want to check if a specific error/warning is triggered by your code.
Tested this with a customised version of `vim-go` (will make a PR there as well to use this new functionality) and it works really well.
=> Add an `include` flag to only include certain messages

README.md, main.go
This commit alters the origin of the deadcode package to a standalone
version which doesn't contain all the other unrelated code that's
present in upstream.
This is important when vendoring the many tools for reproducible builds.
=> Use standalone repo of deadcode command

README.md, main.go
This commit adds lll (Line Length Linter) (https://github.com/walle/lll)
=> Add linter lll

main.go
This PR moves the logic used to print a comma below the logic used to skip warnings when `errorsFlag` is used. Without this change, extraneous commas are printed in the JSON output, causing JSON parsing to fail.
Fixes #101
=> Only Print A Comma When There's An Issue To Print

README.md, main.go
This adds https://github.com/client9/misspell  Since it applies to English (which is not required by golang) and possibility of false positives,  it is disabled by default.  This matches gofmt and lll.  But happy to make it on-by-default.
To test,
first remove misspell if it exists
```
rm `which misspell`
```
test install
```bash
go run main.go --install --update
which misspell
```
test lint by making `junk.go` that contains something like `// TOOD: write code`
```
go run main.go -enable misspell .
```
You should get something like this:
```
junk.go:3:3:warning: found "TOOD:" a misspelling of "TODO:" (misspell)
```
onward!
n
=> Issue alecthomas/gometalinter#118 - add client9/misspell

README.md
I assume this is a typo in the README. A basic test shows that `{path}` is the correct keyword, whereas `{paths}` doesn't do anything special. I tested this via the following command:
gometalinter --vendor --disable-all --linter='vet:bash -c "echo {path} >~/Desktop/proof":PATH:LINE:MESSAGE' --enable=vet .
The above command writes the  `.` (or whatever path you choose to pass to the linter) to the file. Replacing `{path}` with `{paths}` causes "{paths}" to be written to the file, which is clearly not what we want.
=> Change {paths} to {path} in README example

README.md
There is bug which was fixed in parent project, but not in fork and it took too much time for me to understand why it is not working on my machine
=> Add link to fork of deadcode which is really used

.travis.yml, README.md, checkstyle.go, main.go, regressiontests/support.go
Checkstyle is a static code quality analysis tool widely used in Java community. This pull request adds a flag to produce output in checkstyle XML format. New output format is enabled with --output=checkstyle argument, which can be easily extended to support even more output types if the need arises.
Checkstyle format has almost identical structure as JSON that gometalinter already produces. the only difference is mandatory grouping of errors by file name and XML encoding.
Main use-case of this would be gometalinter output integration with Jenkins CI system. Jenkins has a good support for checkstyle output via https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin plugin. It adds static code analysis trend graph and allows browsing detected issues from web interface.
=> Add support for checkstyle output mode

aggregate.go, main.go, regressiontests/structcheck_test.go, regressiontests/support.go
Hi, this PR adds an option that aggregate duplicate messages of the same issue (reported by several linters), it intends to fix #117. Like `--sort`, `--aggregate` can't stream the issues and is an opt-in. It is also compatible with `--sort`.
Two issues are considered equals if the same message is reported for the same location. See examples below.
```
% ls
test.go
% cat test.go
package main
func main() {
println(("hey")
}
% gometalinter --sort line
test.go:4:20:warning: error return value not checked (missing ',' before newline in argument list (and 1 more errors)) (errcheck)
test.go:4:20:warning: unused global variable missing ',' before newline in argument list (and 1 more errors) (varcheck)
test.go:4:20:error: missing ',' before newline in argument list (gotype)
vet: test.go: …
```
=> Aggregate lines

main.go
When I executed `gometalinter --install --update` with the latest gometalinter, it raised error.
```
DEBUG: go install -v -u github.com/HewlettPackard/gas
flag provided but not defined: -u
usage: install [build flags] [packages]
```
`-u` flag and `-f` flag are not defined as `go build` flags.
Append these flags when `gometalinter install` is going to execute `go get`.
=> Append -f and -u flags only with go get

main.go
Running `gometalinter --enable=invalid` results in a panic and stack trace that don't really describe what the issue is:
```panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x26cb00, 0xc4200141e0)
/go/src-1.7/src/runtime/panic.go:500 +0x1a1
main.LinterFromName(0x7fff5fbff1f6, 0x7, 0xc420051df0)
/go/ext/src/github.com/alecthomas/gometalinter/main.go:63 +0x5ff
main.lintersFromFlags(0x0)
/go/ext/src/github.com/alecthomas/gometalinter/main.go:713 +0x9e
main.main()
/go/ext/src/github.com/alecthomas/gometalinter/main.go:290 +0x268
```
With this PR the result is ```gometalinter: error: invalid linter: "invalid"``` followed by the gometalinter usage.
=> Fix issue when invalid linter is specified

README.md
Just updated the README adding the missing gas linter info and link.
=> Added missing gas linter info to README

config.go, main.go
This change makes to support the following configuration file.
```json
{
"Disable": [
"golint",
"gotype"
]
}
```
The configuration file disables `golint` and `gotype`.
=> Configurable disable option

config.go
Currently the `gometalinter --help` indicates that the default value is `runtime.NumCPU()`.
I get this indication from the [placeholder](https://github.com/alecthomas/gometalinter/blob/2c137d148e40e95c566bc68eda12ea21d222e7a8/main.go#L145).
It also runs much better if you don't use `16` threads on a machine that only has 4 cores :) hehe
It was pretty much sucking all the I/O out of my laptop when running some of the more expensive linters like `interfacer`.
I suspect this will be a good default for people running in travis too.
Note: it could also be `runtime.NumCPU()*2`, but since most laptops these days have N cores N*2 logical cores (due to hyper threading), `runtime.NumCPU()` is probably going to be fine.
=> Default concurrency to runtime.NumCPU()

main.go
Only add the directories which aren't already present in PATH and append the first element of GOPATH instead of prepend it.
This prevents failures issues caused by miss-ordered entries in PATH fixing #266.
=> Only add missing directories to PATH

main.go
This should fix the `linterState.fixPath` issue
Found this on *golint* only when using ellipsis on the path ex: `src/github.com/uudashr/fibgo/...`
The fixPath return `src/github.com/uudashr/fibgo/src/github.com/uudashr/fibgo/fib.go` 
while expecting `src/github.com/uudashr/fibgo/fib.go`
Before fix, the debug result:
```
./bin/gometalinter --disable-all --enable=golint --debug src/github.com/uudashr/fibgo/...
DEBUG: PATH=/Users/uudashr/.rbenv/shims:/Users/uudashr/google-cloud-sdk/bin:/Users/uudashr/Applications/apache-maven-3.3.9/bin:/Users/uudashr/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/uudashr/Library/Python/2.7/bin
DEBUG: GOPATH=/Users/uudashr/go
DEBUG: GOBIN=
DEBUG: linting path src/github.com/uudashr/fibgo
DEBUG: linting path …
```
=> Fix the linterState.fixPath issue

config.go, main.go, main_test.go
This change replaces the `DeadlineJSONCrutch` with a type which handles serializing from a JSON string to a `time.Duration()`. Also adds a test to cover the change.
=> Use a duration type instead of deadline crutch

execute.go, linters.go, main.go, regressiontests/support.go
@alecthomas we talked about this in gitter.
I split out a couple new files, one for the running of linters, another for defining and installing linters. Flag handling and output remain in `main.go`.
I also cherry-picked some changes from support.go from #289 to get the regression tests working with the new files.
=> Split main package into more files

config.go, execute.go, execute_test.go, linters.go, main.go, partition.go, partition_test.go
Fixes #318
Some linters don't accept absolute paths, so convert them to package paths.
=> Convert absolute paths to package paths for some linters

main.go, main_test.go, stringset.go
Environment variables are setup for two cases: run and install.
I believe that each case requires different variables. Run only requires `PATH` to be set correctly. Install requires `GOBIN` and `GOPATH` to be set correctly.
This change splits `configureEnvironment()` into two functions. One for run, and one for "install vendored linters". This skips any unnecessary `os.Setenv()` and makes it more obvious which variables are used for which case. Any overlap between these cases should still be shared using extracted functions.
=> Split environment variable setup

config.go
invoked: `gometalinter --vendor --tests --fast --deadline\=5s --checkstyle -d .`
```
[...]
DEBUG: executing /home/cblades/go/bin/gotype -e -a .
DEBUG: warning: /home/cblades/go/bin/gotype returned exit status 2: flag provided but not defined: -a
usage: gotype [flags] [path ...]
The gotype command, like the front-end of a Go compiler, parses and
type-checks a single Go package. Errors are reported if the analysis
fails; otherwise gotype is quiet (unless -v is set).
Without a list of paths, gotype reads from standard input, which
must provide a single Go source file defining a complete package.
With a single directory argument, gotype checks the Go files in
that directory, comprising a single package. Use -t to include the
(in-package) _test.go files. Use -x to type check only external
test …
```
=> fixup! gotype uses the `-t` flag to enable linting of test files

aggregate.go, checkstyle.go, config.go, directives.go, execute.go, linters.go, main.go, partition.go, stringset.go
With this change it should be easier to see the properties of a specific linter. 
I think this change will enable us to support a full linter definition from the config format. Instead of just a list of strings in the form of `name: spec`, we could support a list of boths strings and `LinterConfig` objects. That would allow a user to fully customize a linter, including setting the partition strategy.
If we read the config during `--install` it would also let them set an `InstallFrom`.
=> Convert default linter config from separate maps to a single map of linterConfig

README.md
Discussed in #326, adding a FAQ entry for revgrep, which I use to filter issues between certain git refs, commonly between branch and master or unstaged changes. This helps in ignoring existing issues and just ensure no new issues are added.
=> README.md: Add FAQ entry for filtering issues between branches

linters.go, linters_test.go
Fixes #332 
Apparently golang doesn't let you compare functions so testing for NotNil was the best I could find.
=> Set a default partition strategy for custom linters.

config.go, linters.go, linters_test.go, main.go, main_test.go
This PR allows users to specify command/pattern overrides individually, falling back to the defaults for un-specified portions. 
E.g. here's what my config looked prior to this PR:
```
{
"Linters": {
"unused": "unused -tags integration:PATH:LINE:COL:MESSAGE",
"gosimple": "gosimple -tags integration:PATH:LINE:COL:MESSAGE"
},
"Enable": [
"deadcode",
"varcheck",
"structcheck",
"goconst",
"ineffassign",
"unconvert",
"misspell",
"gosimple",
"unused"
]}
```
here's what it looks like after: 
```
{
"Linters": {
"unused":   { "Command": "unused -tags integration"   },
"gosimple": { "Command": "gosimple -tags integration" }
},
"Enable": [
"deadcode",
"varcheck",
"structcheck",
"goconst",
"ineffassign",
"unconvert",
"misspell",
"gosimple",
"unused"
]}
```
=> Ability to override command/pattern individually per linter

README.md, config.go, config_test.go, linters.go, linters_test.go, partition.go, partition_test.go
Adds support for setting `IsFast` and `PartitionStrategy` from the config file. Technically `InstallFrom` can be set, but it doesn't do anything just yet because `--install` always reads the defaultLinters instead of any config.
Updates the README to document linter settings in the configuration file.
Also adds a `single-directory` partition strategy that might allow for a workaround for #351
=> Support setting of all linter config fields from the config file

linters.go, regressiontests/gotype_test.go
Fixes #355
Using `gotype` will work as it did before, it will only lint the non-external packages. To also lint external packages you should be able to add a second version of `gotype` to the config:
```json
{
"Linters": {
"gotypeexternal": {
"Command": "gotype -x",
"Pattern": "PATH:LINE:COL:MESSAGE",
"PartitionStrategy": "partitionPathsByDirectory"
}
},
"Enable": ["gotypeexternal", ...]
}
```
=> Fix gotype with multi-package directory (restores pre-partition-strategy behaviour)

config.go, directives.go, directives_test.go, execute.go, issue.go, main.go
Fixes #354
Adds a new flag to enable the new behaviour. When the flag is enabled all the files are parsed for directives (otherwise warnings would only exist for files with at least one issue).  Once all linting is done all the ignore ranges are checked and new issues are created for any ignore range that was never matched to an issue.
The order of issue processing operations was changed to filter before sorting so that the new `nolint` issues are properly sorted.
=> Warn on ununsed directive

linters.go, linters_test.go, main.go, main_test.go
Discovered in #369
When an unknown linter is enabled, raise an error identifying which linter(s) are unknown, rather than failing with:
WARNING: invalid command ""
Note: linters defined with the --linter flag are not considered unknown and will not fail with this error.
=> Improve error message in the case of an unknown linter

execute.go, execute_test.go, linters.go
=> Set errcheck -ignoretests when tests are not enabled

_linters/src/honnef.co/go/tools/lint/lint.go, _linters/src/honnef.co/go/tools/lint/lintutil/util.go, _linters/src/honnef.co/go/tools/version/version.go, _linters/src/manifest
Closes https://github.com/alecthomas/gometalinter/issues/389
Commands:
```
gvt delete honnef.co/go/tools
gvt fetch -tag 2017.2 honnef.co/go/tools
```
=> update vendored linter honnef.co/go/tools to tag 2017.2

main.go
Here is a fix for #330 which makes a more readable and useful output for linters when `--help` is called.
=> Fix #330 - better linter formatting

linters.go, regressiontests/gas_test.go
Executing gas with argument only with the path to directory always returns that no files are analyzed:
```
$ gas some-folder
Summary:
Files: 0
Lines: 0
Nosec: 0
Issues: 0
```
In order gas to analyze the files, every file should be given as an argument.
=> Fix gas partition stategy

main.go
I want to use gometalinter as much as possible simple.
I've created an alias, `alias gometalinter=gometalinter --config=~/.config/gometalinter/config.json`.
But It was not so good.
case 1) Switching configurations, I have to type like `\gometalinter --config=...` or `command gometalinter --config=...` (in case of zsh).
case 2) In CIs using docker, gometalinter have to be called as `gometalinter --config=...` for each time.
:
So I think that `gometalinter` should be able to look an envar as a config filename.
[kingpin](https://github.com/alecthomas/kingpin) does not kick `Action` on a flag when it is specified by an envar.
(ref: https://github.com/alecthomas/kingpin/issues/175)
So an envar has to be taken by `os.Getenv()` before `kingpin.Parse`.
=> Take an environment variable as a config filename

config.go, execute.go, linters.go, main.go
This adds a --misspell-locale option to gometalinter. It passes the
desired locale setting to misspell so that you can check for common
typos like "color" which are obviously supposed to read "colour". ;)
Unfortunately there is no Canadian linter at this time, so UK will have
to do for now.
Example:
gometalinter --disable-all --enable=misspell --misspell-locale=UK
=> misspell: Add locale setting to misspell

main.go
It disappeared in b0bb897a0460b9d889dce15fc2b4f64b06e817f8 when #320 moved code around:
https://github.com/alecthomas/gometalinter/pull/320/files?diff=unified#diff-7ddfb3e035b42cd70649cc33393fe32cR163
=> Restore the warning about updating vendored linters

main.go
In order to help debug performance; to help identify time spent in different linters
=> Add timestamp to debug format

.goreleaser.yml
The source was removed from `_linters` but it's still  referenced in the goreleaser config
=> Remove govet from goreleaser config

.goreleaser.yml
You will need to create a separate repository `alecthomas/homebrew-tap`. You can rename it, but it's usually a good idea to have a general naming if you want to add more taps later.
=> feat: Add brew instructions to goreleaser

execute.go
This avoids a data race on `err` between the inner goroutine
and the deadline arm below.
=> Pass error out of goroutine via channel

linters.go
The gosec linter is printing a range expression like `1200-1204` for the
line number in some cases.
The gosec output in csv looks like:
```
/home/fho/git/test/example.go,1200-1204,SQL string formatting,MEDIUM,HIGH,"fmt.Sprintf(`
SELECT
%s,
FROM test
)"
```
The gometalinter line pattern was only expecting one or more digits as line
number.
This caused that some warnings did not match the pattern and did not
show up in the gometalinter results.
The Gosec pattern is changed to parse the first number as line number
and ignore an eventual following `-<NUMBER>` expression.
Gometalinter only supports to work with a single number for lines.
=> linters: fix: multiline gosec warnings not shown in gometalinter result

.goreleaser.yml
Since goreleaser-produced binaries is now the official way
to use stable gometalinter, it makes sense to cover more
GOOS/GOARCH combinations.
Update #552
Signed-off-by: Dmitry Vyukov <dvyukov@google.com>
=> Release freebsd/openbsd/netbsd and arm64 binaries

main.go
If the root path is a symlink dereference it by
appending os.PathSeparator.  Then the os.Lstat()
in filepath.Walk() will correctly see the directory
The root path might be a symlink in order for developers
to place a project under GOPATH without modifying GOPATH.
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
=> resolvePaths: dereference root path symlink

_linters/src/4d63.com/gochecknoglobals/check_no_globals.go, _linters/src/manifest
This fixes the line number for variables inside a 'var' group.
See https://github.com/leighmcculloch/gochecknoglobals/pull/9
=> Update gochecknoglobals to abbdf6ec0afbf03522985f899c67ead98818854d
